package com.ls.converter.json.service;

import com.ls.converter.imagetopdf.model.PdfWriterContext;
import com.ls.converter.common.util.AppUtil;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.util.concurrent.atomic.AtomicInteger;

@Service
public class JsonService {
    private final ObjectMapper objectMapper;
    private final AppUtil appUtil;

    public JsonService(ObjectMapper objectMapper, AppUtil appUtil) {
        this.objectMapper = objectMapper;
        this.appUtil = appUtil;
    }

    public byte[] jsonToPdf(String json) throws Exception{
        JsonNode node = objectMapper.readTree(json);
        try(PDDocument document = new PDDocument();
            ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            PDPage page = new PDPage();
            document.addPage(page);
            try(PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
                contentStream.beginText();
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 18);
                //contentStream.setLeading(15);
                contentStream.newLineAtOffset(40, 750);
                contentStream.showText("JSON REPORT");
                contentStream.newLineAtOffset(0 , -25);
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 10);
                contentStream.showText("Generated On :" + LocalDateTime.now());
                contentStream.newLineAtOffset(0 , -15);
                contentStream.showText("Generated By : JSON Converter");
                contentStream.newLineAtOffset(0, -30);
                PdfWriterContext context= new PdfWriterContext(
                        document,
                        page,
                        contentStream,
                        750
                );
                appUtil.writeNode(node, "", context);
                context.getContentStream().endText();
                context.getContentStream().close();
                document.save(out);
                return out.toByteArray();
            }
        }catch (Exception e){
            throw new RuntimeException(e.getMessage());
        }
    }

    //JSON-TO-EXCEL
    public byte[] jsonToExcel(String json) throws Exception {
        JsonNode root = objectMapper.readTree(json);
        try(XSSFWorkbook workbook = new XSSFWorkbook();
            ByteArrayOutputStream out = new ByteArrayOutputStream()){
            Sheet sheet = workbook.createSheet("Data");
            AtomicInteger rowNum = new AtomicInteger(0);
            appUtil.writeExcelNode(root, "" , sheet, rowNum);
            workbook.write(out);
            return out.toByteArray();
        }
    }

    public byte[] jsonToWord(String json) throws Exception {
        try {
            JsonNode root = objectMapper.readTree(json);
            return appUtil.createWord(root);
        }catch (Exception e){
            throw new RuntimeException(e.getMessage());
        }
    }
}
